### ISSUE TITLE
demo link is showing blank

### ISSUE THREAD

**Issue by arunpratap26** [conficient/BlazorDynamicList#3]
demo is hosted at https://blazordynamiclist.azurewebsites.net  is not working

![Untitled](https://user-images.githubusercontent.com/47097845/59490900-6e214b80-8ea3-11e9-96f0-62a973e1d5ba.png)

**Comment by conficient** [comment]
Thanks for the warning, I was aware - it seems preview 6 has issues when publishing Blazor apps - see https://github.com/aspnet/AspNetCore/issues/10878 - I've intentionally left it broken until this is fixed

**Comment by arunpratap26** [comment]
thank you should I close this issue or you will?

**Comment by conficient** [comment]
I'll close it when MS fixes the cause and the site is working again, thx

**Comment by conficient** [comment]
Found a fix for this issue and demo site is now working again
